/*
 * This is the definition of the musician schema
 * This schema belongs to a PostgresSQL database.
 */

create table musician.band
(
    id      bigint generated by default as identity
        primary key,
    founded date,
    genre   varchar(255),
    name    varchar(255),
    salary  numeric(15, 2)
);

comment on table musician.band is 'contains bands';

comment on column musician.band.name is 'name of the band';

create table musician.musician
(
    id         bigint generated by default as identity
        primary key,
    birth_date date,
    first_name varchar(255),
    instrument varchar(255),
    last_name  varchar(255)
);

create table musician.musician_band
(
    musician_id bigint not null
        constraint fklds1memsv6mn7jp3u4hn8m8kc
            references musician.musician,
    band_id     bigint not null
        constraint fk35axkw9d9md6e08xaw4kxkf6t
            references musician.band
);

create view musician.vmusicians
            (musician_id, first_name, last_name, instrument, band_id, name, genre) as
SELECT mb.musician_id,
       m.first_name,
       m.last_name,
       m.instrument,
       mb.band_id,
       b.name,
       b.genre
FROM musician.musician m
         LEFT JOIN musician.musician_band mb ON m.id = mb.musician_id
         LEFT JOIN musician.band b ON b.id = mb.band_id;

comment on view musician.vmusicians is 'list of bands and their members';

