create table band
(
    id      bigint generated by default as identity
        primary key,
    founded date,
    genre   varchar(255),
    name    varchar(255)
);

alter table band
    owner to postgres;

create table musician
(
    id         bigint generated by default as identity
        primary key,
    birth_date date,
    first_name varchar(255),
    instrument varchar(255),
    last_name  varchar(255)
);

alter table musician
    owner to postgres;

create table musician_band
(
    musician_id bigint not null
        constraint fklds1memsv6mn7jp3u4hn8m8kc
            references musician,
    band_id     bigint not null
        constraint fk35axkw9d9md6e08xaw4kxkf6t
            references band
);

alter table musician_band
    owner to postgres;

